# Generated by Django 2.2 on 2019-04-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articale',
            new_name='Article',
        ),
    ]
